decoupled-dj/billing/urls.py
from django.urls import path
from .views import Index
from .api.views import ClientList, InvoiceCreate

app_name = "billing"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("api/clients/", ClientList.as_view(), name="client-list"),
    path("api/invoices/", InvoiceCreate.as_view(), name="invoice-create"),
]

decoupled-dj/decoupled_dj/urls.py
from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.urls import path, include

from django.conf import settings # added new

urlpatterns = [
        path("billing/", include("billing.urls", namespace="billing")),
        path("auth/", include("login.urls", namespace="auth"))
    
    ]

# -------------------
# added ramdomness to admin url to mitigate automated brute force attacks

if settings.DEBUG:
    urlpatterns = [
        path("admin/", admin.site.urls),
    ] + urlpatterns

if not settings.DEBUG:
    urlpatterns = [
        path("77randomAdmin@33/", admin.site.urls),
    ] + urlpatterns

# -------------------

decoupled-dj/login/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


app_name = "auth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="login/login.html", redirect_authenticated_user=True
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
]

decoupled-dj/billing/models.py
# from django.db import models

# Create your models here.

from django.db import models
from django.conf import settings


class Invoice(models.Model):
    class State(models.TextChoices):
        PAID = "PAID"
        UNPAID = "UNPAID"
        CANCELLED = "CANCELLED"

    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    date = models.DateField()
    due_date = models.DateField()
    state = models.CharField(max_length=15, choices=State.choices, default=State.UNPAID)


class ItemLine(models.Model):
    invoice = models.ForeignKey(
        to=Invoice, on_delete=models.PROTECT, related_name="items"
    )
    quantity = models.IntegerField()
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    taxed = models.BooleanField()

decoupled-dj/login/models.py
from django.db import models

# Create your models here.

decoupled-dj/users/models.py
# from django.db import models

# Create your models here.

# Create a Custom user
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField

class User(AbstractUser):
    name = CharField(blank=True, max_length=100)

    def __str__(self):
        return self.email

decoupled-dj/billing/api/views.py
from .serializers import InvoiceSerializer
from .serializers import UserSerializer, User
from rest_framework.generics import CreateAPIView, ListAPIView
from rest_framework.permissions import IsAuthenticated # added new

class ClientList(ListAPIView):
    permission_classes = [IsAuthenticated]
    
    serializer_class = UserSerializer
    queryset = User.objects.all()


class InvoiceCreate(CreateAPIView):
    serializer_class = InvoiceSerializer

decoupled-dj/billing/views.py
# from django.shortcuts import render

# Create your views here.

from django.views.generic import TemplateView

from django.contrib.auth.mixins import LoginRequiredMixin # newly added

# class Index(TemplateView):
class Index(LoginRequiredMixin, TemplateView): # revised
    template_name = "billing/index.html"

decoupled-dj/login/views.py
from django.shortcuts import render

# Create your views here.

decoupled-dj/billing/templates/billing/index.html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="/static/billing/favicon.ico">
    <title>vue_spa</title>
  <script defer src="/static/billing/js/chunk-vendors.js"></script><script defer src="/static/billing/js/app.js"></script></head>
  <body>
    <noscript>
      <strong>We're sorry but vue_spa doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>

decoupled-dj/decoupled_dj/deployment/templates/decoupled-django.com-trustme.j2
upstream gunicorn {
    server {{ upstream_addr }};
}

server {
    server_name {{ domain }};
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    server_name {{ domain }};
    listen 443 ssl;

    # access_log <= configure this
    # error_log <= configure this

    ssl_certificate /home/{{ user }}/server.pem;
    ssl_certificate_key /home/{{ user }}/server.key;

    location / {
        alias /home/{{ user }}/code/billing/vue_spa/dist/;
    }

    location /auth/ {
        proxy_pass http://gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* /api/ {
        proxy_pass http://gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    server_name static.{{ domain }};
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    server_name static.{{ domain }};
    listen 443 ssl;

    ssl_certificate /home/{{ user }}/server.pem;
    ssl_certificate_key /home/{{ user }}/server.key;

    location / {
        alias /home/{{ user }}/code/static/;
    }
}

decoupled-dj/decoupled_dj/deployment/templates/decoupled-django.com.j2
upstream gunicorn {
    server {{ upstream_addr }};
}

server {
    server_name {{ domain }};
    ## If you use Let's Encrypt, SSL configuration is managed by Certbot
    # access_log <= configure this
    # error_log <= configure this

    location / {
        alias /home/{{ user }}/code/billing/vue_spa/dist/;
    }

    location /auth/ {
        proxy_pass http://gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~* /api/ {
        proxy_pass http://gunicorn;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


server {
    server_name static.{{ domain }};
    ## If you use Let's Encrypt, SSL configuration is managed by Certbot

    location / {
        alias /home/{{ user }}/code/static/;
    }
}

decoupled-dj/decoupled_dj/deployment/templates/gunicorn-service.j2
[Unit]
Description=decoupleddjango gunicorn
After=network.target

[Service]
Environment=DJANGO_SETTINGS_MODULE=decoupled_dj.settings.production
User={{ user }}
Group={{ user }}
WorkingDirectory=/home/{{ user }}/code
ExecStart=/home/{{ user }}/code/venv/bin/gunicorn decoupled_dj.asgi:application -w 2 -k uvicorn.workers.UvicornWorker -b {{ upstream_addr }}

[Install]
WantedBy=multi-user.target

decoupled-dj/login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form method="POST" action="{% url "auth:login" %}">
    {% csrf_token %}
    <div>
        <label for="{{ form.username.id_for_label }}">Username:</label>
        <input type="text" name="username" autofocus maxlength="254" required id="id_username">
    </div>
    <div>
        <label for="{{ form.password.id_for_password }}">Password:</label>
        <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
    </div>
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" value="login">
        LOGIN
    </button>
</form>
{{ form.non_field_errors }}
</body>
</html>